---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ .Chart.Name }}-web
  namespace: {{ .Release.Namespace }}
  annotations:
    {{ if .Values.ingress.annotations }}
    {{ toYaml .Values.ingress.annotations | nindent 4 }}
    {{ end }}
spec:
  {{- if .Values.ingress.tls }}
  tls:
    {{- toYaml .Values.ingress.tls | nindent 4 }}
  {{- end }}
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ $.Values.phpipam.name }}
                port:
                  number: {{ $.Values.phpipam.service.port }}
          {{- end }}
    {{- end }}
