{{- if .Values.database.installed }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Chart.Name }}-mysql
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.database.persistence.size }}
{{- if .Values.database.persistence.storageClassName }}
  storageClassName: "{{ .Values.database.persistence.storageClassName }}"
{{- end }}
{{- end }}
