{{- if .Values.database.installed }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.database.name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
      component: mysql
  serviceName: {{ .Values.database.name }}
  template:
    metadata:
      name: {{ .Values.database.name }}
      labels:
        app: {{ .Chart.Name }}
        component: mysql
    spec:
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Values.database.name }}
          image: "{{ .Values.database.image.repository }}:{{ .Values.database.image.tag | default .Chart.AppVersion }}"
          ports:
            - containerPort: {{ .Values.database.service.port }}
              protocol: TCP
              name: mysql
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
            - name: mysql-config
              mountPath: /etc/mysql/conf.d
          env:
            - name: "MYSQL_ROOT_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-{{ .Chart.Name }}-secrets
                  key: {{ .Chart.Name }}-mysql-root-pass
            - name: "MYSQL_LOG_CONSOLE"
              value: "true"
            - name: "MYSQL_DATABASE"
              value: {{ .Values.global.database.name }}
            - name: "MYSQL_USER"
              value: {{ .Values.global.database.user }}
            - name: "MYSQL_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-{{ .Chart.Name }}-secrets
                  key: {{ .Chart.Name }}-mysql-pass
          resources:
            {{- toYaml .Values.database.resources | nindent 12 }}
      volumes:
      - name: mysql-data
        persistentVolumeClaim: 
          claimName: {{ .Chart.Name }}-mysql
      - name: mysql-config
        configMap:
          name: {{ .Release.Name }}-{{ .Chart.Name }}-mysql-config
          items:
            - key: my.cnf
              path: mysql-custom.cnf
{{- end }}
